# Generated by Django 6.0.4 on 2026-04-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_sku'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm;",
        ),
    ]
