# Generated by Django 6.0.4 on 2026-04-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_enable_pg_trgm'),
    ]

    operations = [
    ]
